#!/bin/sh -x

# create copies from templates
sed "s/%s/$1/g" ~/.bin/vue-component/script.js > script
sed "s/%s/$1/g" ~/.bin/vue-component/template.jade > template
sed "s/%s/$1/g" ~/.bin/vue-component/stylesheet.styl > stylesheet
sed "s/%s/$1/g" ~/.bin/vue-component/computed-styles.js > styles

# ensure valid directory structure exists
mkdir -p js/components/$1
mkdir -p jade/components
mkdir -p stylus/components

mv script js/components/$1/vm.js
mv template jade/components/$1.jade
mv stylesheet stylus/components/$1.styl
mv styles js/components/$1/computed-styles.js

echo "@import 'components/$1'" >> stylus/style.styl