#!/bin/sh -x

# create copies from templates
sed "s/%s/$1/g" ~/.bin/vue-component/script.js > script
sed "s/%s/$1/g" ~/.bin/vue-component/template.jade > template
sed "s/%s/$1/g" ~/.bin/vue-component/stylesheet.styl > stylesheet

mkdir -p js/components/$1

mv script js/components/$1/$1.js
mv template jade/components/$1.jade
mv stylesheet stylus/components/$1.styl

cp computed-styles.js js/components/$1/computed-styles.js